README.md, src/Scaffold_Command.php
tab -> spaces for indenting list item in docs
=> whitespace fix

templates/plugin-travis.mustache
=> Ensure PHPUnit 5.7.* is installed for PHP nightly on Travis.

src/Scaffold_Command.php
=> Fixed notice when CI not passed to scaffold

templates/plugin-circle.mustache
=> Test PHP 7 versions in scaffolded `circle.yml`

.gitignore
Add `composer.lock` to `.gitignore`
=> ignore composer.lock

templates/install-wp-tests.sh
=> Use `$TMPDIR` to allow temp directory override

features/install-wp-tests.feature
=> run install-wp-tests.sh of the scaffolded new plugin

src/Scaffold_Command.php
=> Added comma after last array item

templates/plugin-travis.mustache
See https://github.com/wp-cli/scaffold-package-command/issues/142
=> Remove XDebug in scaffolded `.travis.yml` to improve performance

templates/plugin-distignore.mustache
=> add package-lock.json, yarn.lock to distignore template

features/scaffold-taxonomy.feature
=> Add a test case for a scenario covered by Doctrine

src/Scaffold_Command.php, src/WP_CLI/Inflector.php
Related: https://github.com/wp-cli/scaffold-command/pull/54#issuecomment-334154258
=> change namespece of the Inflector

templates/plugin-gitlab.mustache
=> Add php 7.0 and 7.1 to gitlab ci

templates/phpunit.xml.dist
=> Add XML declaration to phpunit.xml.dist

features/scaffold-taxonomy.feature, templates/taxonomy_extended.mustache
=> Add `term_updated_messages` to scaffolded taxonomies

features/scaffold.feature, templates/plugin-gitignore.mustache
=> Add standard test configs to .gitignore

templates/plugin-bootstrap.mustache
=> Use updated error message in `bootstrap.php`

.travis.yml, composer.json, features/bootstrap/FeatureContext.php, features/bootstrap/Process.php, features/bootstrap/utils.php, features/install-wp-tests.feature, features/scaffold-plugin-tests.feature, features/scaffold-theme-tests.feature, features/scaffold.feature, features/steps/then.php, features/steps/when.php, utils/behat-tags.php
See https://github.com/wp-cli/wp-cli/pull/4515
=> Update scaffolded tests to enable error reporting

templates/plugin-travis.mustache
=> Template: Remove composer vendor directory from Travis CI cache

.travis.yml
=> Travis CI: Remove composer vendor directory from Travis CI cache

templates/taxonomy.mustache, templates/taxonomy_extended.mustache
update code to remove WPCS warnings in taxonomy generation #109
=> fix wpcs in taxonomy generation

templates/child_theme_functions.mustache
update code to remove WPCS warnings in child theme generation #109
=> fix wpcs in child theme generation

templates/theme-bootstrap.mustache, templates/theme-test-sample.mustache
update code to remove WPCS warnings in `theme-tests` generated files #109
=> fix wpcs in theme-tests generation

features/scaffold-block.feature, src/Scaffold_Command.php, templates/block-php.mustache
=> Fix theme-specific paths in scaffolded blocks

features/install-wp-tests.feature, features/scaffold-theme-tests.feature
=> Skip PHPUnit tests for PHP 7.2+

src/Scaffold_Command.php, templates/block-index-js.mustache
=> Add escaping for block title

templates/taxonomy.mustache
fixes https://github.com/wp-cli/scaffold-command/issues/160
=> Correct add_new_item label

templates/post_type.mustache
=> Inc 'menu_position' when scaffolding a post type

templates/post_type_extended.mustache
=> Missing text domain in post_type_extended.mustache

features/install-wp-tests.feature
=> Split up the list of expected files to allow for WP 5.0+ changes

src/Scaffold_Command.php
* No assignments in conditions.
=> PHPCS: fix up the code base [4] - assignments in conditions

composer.json
=> Fix: Document PHP version requirements

.travis.yml, features/scaffold.feature
1. try:
- Switch from `trusty` to `xenial`.
Fixes #244
=> Fix Travis TLS handshake error

features/scaffold-block.feature, templates/block-php.mustache
Add child theme support when scaffolding block.
Fixes #232
=> Scaffold block support for child theme.

composer.json
=> Updated minimum required PHP version to 5.6

templates/post_type_extended.mustache
=> Add a callback for the bulk messages for post-types

.github/workflows/testing.yml, templates/install-wp-tests.sh
@schlessera this should fix the branch you posted in WordPress Slack, pending merge of https://github.com/wp-cli/wp-cli-tests/pull/115
For initial run I have included that here. I will then remove it once those works are merged and it should stay green.
I Tidied up the commit log, as this was originally a total experiment conducted mostly using web interface.
=> Add missing clean-up in `templates/install-wp-tests.sh`

.github/workflows/testing.yml, behat.yml, composer.json, features/install-wp-tests.feature, features/scaffold-block.feature, features/scaffold-plugin-tests.feature, features/scaffold-taxonomy.feature, features/scaffold-theme-tests.feature, features/scaffold.feature, src/Scaffold_Command.php, templates/block-php.mustache, templates/child_theme_functions.mustache, templates/install-wp-tests.sh, templates/plugin-bootstrap.mustache, templates/plugin-circle.mustache, templates/post_type.mustache, templates/post_type_extended.mustache, templates/taxonomy.mustache, templates/taxonomy_extended.mustache, templates/theme-bootstrap.mustache
Making scaffolding of tests work with PHP 8.0 goes way beyond the scope of this PR and has been extracted into its own issue: #285
=> Add updated GHA testing workflow

.distignore
=> .distignore: ignore `.github` directory

features/install-wp-tests.feature, templates/phpunit.xml.dist
Should fix tests for plugin scaffolding.
=> Add testsuite name in `phpunit.xml.dist`

features/install-wp-tests.feature
See https://github.com/wp-cli/wp-cli/issues/5810
=> Only install trunk on PHP 7.0+

templates/plugin.mustache
This commit adds a mandatory security check at the beginning of the main plugin file.
=> Adds ABSPATH check in plugin.mustache file
