wp-cli/scaffold-command

- templates/plugin-travis.mustache
See https://github.com/wp-cli/media-command/issues/11
> Fix master template for Travis CI composer caching

- .travis.yml
- src/Scaffold_Command.php
Instead of relating the `/templates/` path to the (relatively) shifting WP-CLI framework, relate it to the command's root folder instead.
See #10
> Use path relative to command to retrieve templates.

- src/Scaffold_Command.php
Always normalize slashes in paths before any comparison for cross–platform compat.
Fixes https://github.com/wp-cli/wp-cli/issues/3939
> Normalized paths before comparison

- features/scaffold-plugin-tests.feature
- features/scaffold-theme-tests.feature
- src/Scaffold_Command.php
Issue https://github.com/wp-cli/scaffold-command/issues/22
Adds `canonicalize_path()` and uses in `check_target_directory()` in place of `realpath()` to avoid symbolic link issues.
Adds some feedback by appending various reasons to the "Invalid plugin/theme slug specified." error messages. Involves changing `check_target_directory()` to return error string instead of bool.
> Cater for symbolic links. Add canonicalize_path and use in check_target_directory.

- templates/plugin-gruntfile.mustache
Related issue - #27 
Changed the grunt config for addtextdomain to override all text domains by default, instead of just appending to all i18n functions.
> Change the grunt config for addtextdomain to override all text domains by default

- templates/install-wp-tests.sh
This PR scans the latest releases and gets the most up to date release when a 2 digit version is specified.  To force the use of the original release, one can specify `.0`, for example `4.7.0`.  Also fetches the latest test suite.
Builds on https://github.com/wp-cli/scaffold-command/pull/34
Fixes #18
> Use latest branch for test library, and always get the latest major release when 2 digit wp versions are used

- src/Scaffold_Command.php
> Transform spaces to underscores when scaffolding a child theme

- templates/plugin-gruntfile.mustache
* remove unused `banner` variable (`'banner' is assigned a value but never used.`)
* ignore `.git` dir
* reference correct tests dir (`php-tests` > `tests`)
Negating globbing patterns in `addtextdomain.update_all_domains` work but do not seem to have any effect on the makepot task (reproducible by putting a php file with a `__()` call in e.g. `bin` and running `grunt i18n --verbose`). Adding an `exclude` param to the `makepot` task seems to be the only way to have the dirs and files within them effectively ignored.
> Grunt i18n: unused var, ignored dirs

- templates/plugin-bootstrap.mustache
- templates/theme-bootstrap.mustache
This will help new users realise that they need to run install-wp-tests.sh before running the tests.
> Improve error message when running phpunit

- src/Doctrine/Common/Inflector/Inflector.php
- src/Scaffold_Command.php
Relates to #48, added Doctrine Inflector class and replaced exiting method `pluralize` .
I considered adding unit test, but didn't add. Because `pluralize` is just an alias for Inflector's method  which is [fully tested](https://github.com/doctrine/inflector/blob/master/tests/Doctrine/Tests/Common/Inflector/InflectorTest.php).
> Enhance pluralization

- templates/phpcs.xml.dist
Displays the progress meter to help identify that phpcs is working.
Closes #62.
> CS: Show progress when invoking phpcs

- templates/plugin-bootstrap.mustache
The default value of `$TMPDIR` is not `/tmp` on macOS.
Related: https://github.com/wp-cli/scaffold-command/pull/61
> get correct WP_TESTS_DIR on mcOS by default

- features/scaffold.feature
- src/Scaffold_Command.php
Related https://github.com/wp-cli/scaffold-command/issues/66
`--dashicon=dashicon-info`, `--dashicon=dashicons-info` and  `--dashicon=info`
will be `'menu_icon'         => 'dashicons-info'`.
> Trim dashicon string

- templates/plugin-travis.mustache
Allows installation of PHPUnit 5.7 instead of 4.8 when running PHP 5.6. Closes #74.
> Travis: allow Composer to determine PHPUnit version

- bin/install-package-tests.sh
- features/install-wp-tests.feature
Closes https://github.com/wp-cli/scaffold-command/issues/80
Uses `wp_cli_test/password1` instead of `root/<no-password>` in a number of tests in `features/install-wp-tests.feature` to make it more convenient to run these tests locally. Also renames the test db to `wp_cli_test_scaffold` from `wordpress_behat_test`, to match up more with `wp_cli_test` I guess.
Requires the test user to run the mysql command
```
GRANT ALL PRIVILEGES ON wp_cli_test_scaffold.* TO "wp_cli_test"@"localhost" IDENTIFIED BY "password1";
```
> Use wp_cli_test/password1 instead of root/no-password in install-wp-tests.feature.

- templates/plugin-gruntfile.mustache
The default task makes running `grunt` useful, instead of producing an
error.
> Add a default task to scaffolded `Gruntfile.js`

- README.md
- features/scaffold-block.feature
- src/Scaffold_Command.php
- templates/block-block-js.mustache
- templates/block-editor-css.mustache
- templates/block-php.mustache
- templates/block-style-css.mustache
This PR  tries to improve the experience for the future block implementers by adding inline documentation based on the [Gutenberg Handbook](https://wordpress.org/gutenberg/handbook/). 
Initial suggestion came from @danielbachhuber in https://github.com/wp-cli/scaffold-command/issues/88#issuecomment-347580892:
> Another idea to throw into the mix: Add jsDoc to the scaffolded `edit` and `save` functions that provides an introductory overview to the functions and then links to the corresponding handbook docs.
In addition, I added the following changes:
- Added CSS styles loaded for both editor and fronted.
- Added a note that a recommended way is to generate a block inside a plugin.
- Fixed a few linting errors for generated PHP and JS files.
- Update API to use a new way of setting …
> Block: Improve in file documentation to make it easier to edit content

- features/scaffold-block.feature
- templates/block-php.mustache
This PR updates PHP template generated with `wp scaffold block` command. It adds changes introduced by @aduth in https://github.com/WordPress/gutenberg/pull/4039. Both ways are still supported, but the new one is the preferred one.
Generated output after changes introduced:
```php
<?php
/**
* Functions to register client-side assets (scripts and stylesheets) for the Gutenberg block.
*
* @package books
*/
/**
* Enqueues all block assets to apply both on the front of your site and in the editor.
*
* @see https://wordpress.org/gutenberg/handbook/blocks/writing-your-first-block-type/#enqueuing-block-scripts
*/
function my_book_block_init() {
$dir = dirname( __FILE__ );
$block_js = 'my-book/block.js';
wp_register_script(
'my-book-block-editor',
plugins_url( $block_js, __FILE__ ),
array( …
```
> Block: Update PHP template to use the server script and style api

- features/scaffold-theme-tests.feature
- templates/theme-bootstrap.mustache
Closes #114 
Adds `theme_root` filter to `templates/theme-bootstrap.mustache` (tests/bootstrap.php) to make sure theme's `functions.php` gets loaded.
> Filter theme_root in tests/bootstrap.php.

- composer.json
- features/bootstrap/FeatureContext.php
- features/bootstrap/Process.php
- features/bootstrap/utils.php
- utils/behat-tags.php
Refreshes test suite and normalizes composer.json, requiring `wp-cli/wp-cli` ^1.5.
1.1.2 pre-release changes for WP-CLI 1.5.0.
> v1.1.2 prerelease: refresh test suite, require wp-cli ^1.5.

- .travis.yml
See https://github.com/wp-cli/scaffold-command/pull/118#issuecomment-366536116 and https://core.trac.wordpress.org/ticket/43218
Temporary fix to use phpunit 6.5.6 if PHP 7.2 until the core test suite is made ~PHP 7.2~ phpunit 7.0.0 compat. Will need to be merged into outstanding PRs.
> Use phpunit 6.5.6 for PHP 7.2 to get around core test incompat.

- templates/theme-bootstrap.mustache
Related: #67 
correct WP_TESTS_DIR, similarly https://github.com/wp-cli/scaffold-command/blob/master/templates/plugin-bootstrap.mustache#L8-L17
> get correct WP_TEST_DIR. Similarly plugin-bootstrap.mustache.

- .distignore
- features/scaffold-plugin-tests.feature
- features/scaffold-theme-tests.feature
- features/scaffold.feature
- src/Scaffold_Command.php
- templates/plugin-circle.mustache
- templates/plugin-distignore.mustache
- templates/plugin-readme.mustache
Fixes #52.
This is a first draft at converting the CircleCI template from using CircleCI 1.0 to 2.0
Notes:
1. I haven't looked into optimizing the config yet. Just trying to do a basic conversion.
2. The PHP Docker images are locked to PHP vX.Y, not a specific bug release. We can change that if the project owners decide they specifically want a full vX.Y.Z.
3. I don't know Mustache well so this config may not be proper syntax for Mustache.
4. I haven't run this config nor tested it yet. I plan to soon but others can join in as well. ;)
5. The new config file should be located at ./.circleci/config.yml instead of ./circle.yml. How would I get that to work here?
> [WIP] Switch CircleCI template to CircleCI 2.0.

- templates/install-wp-tests.sh
The -i syntax is: `-i[SUFFIX]`. There should be no space between `-i`
and the suffix. See [sed Command Line Options](https://www.gnu.org/software/sed/manual/sed.html#Command_002dLine-Options-1).
Before this fix, I saw the following error on macOS:
```
sed: -e expression #1, char 1: unknown command: `.'
```
> Fix sed -i option

- .travis.yml
The Behat tests are currently running out of memory in PHP 5.3 environments, as noted by @schlessera in wp-cli/entity-command#161.
This uses the same code as wp-cli/entity-command@f449ea9 to raise the memory_limit within Travis' PHP configuration.
> Bump the Travis CI memory limit to 2048MB

- features/scaffold-plugin-tests.feature
- features/scaffold-theme-tests.feature
- templates/phpunit.xml.dist
This commit adds ./tests/test-sample.php as an exclusion in the phpunit.xml.dist file, preventing it from executing by default when developers run PHPUnit.
Keeping the sample file can be helpful for projects (for instance, if the project is using a custom base test case and/or namespaces), but constantly asserting that true is, in fact, true isn't helpful.
> Exclude tests/test-sample.php via the phpunit.xml.dist file

- templates/block-php.mustache
Check for the existance of the function register_block_type() in the PHP
code when creating a block.
Since Gutenberg has not yet been merged into core, currently the function
register_block_type() is only defined if the Gutenberg plugin is installed
and activated.
See #146
> Add function_exists() check to block PHP template

- templates/plugin-circle.mustache
Reduces the redundancy in the Circle CI file making it easier to add additional PHP jobs. See #148
> Refactor circleci with aliases to reduce redundancy

- templates/block-php.mustache
`wp-blocks` dependency is not required by block
https://github.com/WordPress/gutenberg/pull/6778
https://wordpress.org/gutenberg/handbook/blocks/generate-blocks-with-wp-cli/#examples
> Remove 'wp-blocks' from style dependency

- features/scaffold.feature
- templates/phpcs.xml.dist
Add PHPCompatibility sniffs to scaffolded
fixes #60
> Add PHPCompatibility sniffs to scaffolded

- features/scaffold.feature
- src/Scaffold_Command.php
Added the new --woocommerce flag to the scaffold _s command.
First time writing behat tests, so hopefully I got them right. The only test I wrote was basically to assert two of the WooCommerce files existed. Not sure if the tests should be more in depth than that, or if there should also be a test to assert the WooCommerce files _don't_ exist when the flag isn't present.
> fixes #139 adding --woocommerce flag to scaffold _s command

- templates/plugin-bootstrap.mustache
The bootstrap.php file generates an error in wpcs sniff because there are two unescapped items. This error is generated with the WordPress files are not loaded by the bootstrap file, so the escape functions are not available.
The solve is to use a line comment that will prevent that from generating an error in the sniff.
addresses https://github.com/wp-cli/scaffold-command/issues/109
> Exclude string from escape warning

- templates/.phpcs.xml.dist
As reported by @dimadin on [Slack](https://wordpress.slack.com/archives/C02RP4T41/p1534097387000006), when using the current `.phpcs.xml.dist` ruleset, a
`phpcs: Ruleset <path>/.phpcs.xml.dist is not valid`
error is thrown.
This was caused by an unclosed comment in the XML. This PR fixes it.
The PR can be tested by:
1. Save the current ruleset locally and try to use it to see the error.
2. Save the ruleset from this PR and try again. The ruleset error will be gone.
> PHPCS template: fix XML error in ruleset

- templates/block-php.mustache
fixes https://github.com/wp-cli/scaffold-command/issues/175
> Fix syntax error in block-php.mustache

- features/scaffold.feature
Related to [#4541](https://github.com/wp-cli/wp-cli/issues/4541) in wp-cli.
> Allow for `installation` as well as `install`

- templates/.phpcs.xml.dist
The `wp-i18n` node module has some PHP that gets flagged.
> Ignore 'node_modules' in PHPCS XML file

- features/scaffold.feature
- src/Scaffold_Command.php
When the request fails on HTTPS, we switch to HTTP instead, which should work within Travis.
Fixes #181
> Work around Travis CI issue with _s download certificate

- templates/install-wp-tests.sh
if `0.0-beta1` use `WP_TEST_TAG=branches/0.0` and `ARCHIVE_NAME` is `wordpress-0.0-beta1`.
RC release is the same as Beta release.
> In the case of RC and Beta, use Branch for WP_TEST_TAG.

- templates/plugin-circle.mustache
Doing so ensures environment variables are passed through and avoids
cryptic build failures.
See https://github.com/docker-library/php/issues/750#issuecomment-439364320
> Run `docker-php-ext-install` with `sudo -E` in CircleCI

- templates/plugin-distignore.mustache
Specifically:
* `.babelrc`
* `.eslintignore`
* `.eslintignore`
* `.eslintignore`
> Ignore various JavaScript config files in plugin `.distignore`

- templates/plugin-distignore.mustache
`dependencies.yml` corresponds with [Dependencies.io](https://www.dependencies.io/)
> Add `dependencies.yml` to plugin `.distignore`

- .travis.yml
- features/install-wp-tests.feature
> Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`

- src/Scaffold_Command.php
When calling a function, it is nonsensical to assign the value of the parameter being passed to a variable _within the function call_, especially if that variable isn't used anywhere else.
This is just not a thing in PHP.
Looking at the code, it looks like this was done to document what the parameters meant.
With that in mind, I've kept the variable assignments, but moved them out of the function call.
Alternatively, the meaning of the passed parameters could just be documented via inline trailing `// [TYPE] message.` comments.
> QA: don't unnecessarily create variables within a function call

- src/Scaffold_Command.php
* Use strict comparisons.
* Use the `$strict` parameter when calling `in_array()`.
> PHPCS: fix up the code base [3] - strict comparisons

- src/Scaffold_Command.php
* Always specify visibility for all class properties and methods.
> PHPCS: fix up the code base [2] - scope modifiers

- src/Scaffold_Command.php
`array_merge()` is a "heavy" function in PHP and is not actually needed to achieve the desired result in this case.
> QA: don't unnecessarily use array_merge()

- src/Scaffold_Command.php
Simple, mostly whitespace related, fixes to make the code comply with the WPCliCS rules.
* Use single quoted strings when the string doesn't contain a single quote or variables.
* Align the equality operators in assignment blocks.
* No space between `else` and `if` for an `elseif`.
* One space on the inside of open/close parenthesis when there is content between them.
* Associative arrays with more than one item, should be multi-line.
* The double arrow in multi-line arrays should be aligned.
* Each array item in a multi-line array should be followed by a comma.
* When using array indexes, use no space on the inside of the square brackets when the index is a string or integer and use one space on the inside of the square brackets otherwise.
* Use tabs …
> PHPCS: fix up the code base [1] - whitespace & inline control structures

- src/Scaffold_Command.php
Multi-line function calls need to have each argument on a new line.
In a next iteration of this principle, it is expected that a sniff will be introduced  to ban multi-line function call arguments.
With this mind, a number of function calls with multi-line parameters which are  currently already causing errors to be thrown by PHPCS, have been fixed by moving  multi-line function call arguments out of the function call and defining these as a  variable before passing it to the function call.
> PHPCS: fix up the code base [5] - multi-line function calls

- src/Scaffold_Command.php
* Use strict comparisons.
This fix was previously merged already via #209, but this got undone by the master-merge-back in #207.
> PHPCS: fix up the code base [3] - strict comparisons (second try)

- .distignore
- .gitignore
- composer.json
- phpcs.xml.dist
This basically adds a PHPCS ruleset using the new WPCliCSstandard.
Please see the individual commits for more detail.
The build for this PR won't be able to pass until wp-cli-tests 2.1 has been released, upon which time, the build can just be restarted and should be green ;-)
Fixes #219
> Implement CS checking based on the WPCliCS ruleset

- features/scaffold-block.feature
- src/Scaffold_Command.php
The purpose of this PR is to prevent nonworking gutenberg blocks.
More details here: https://github.com/wp-cli/scaffold-command/issues/191
> Prevent creating unregisterable blocks due to invalid plugin slug

- .travis.yml
> Fix: Move PHP version configuration to stage

- src/Scaffold_Command.php
- templates/plugin-packages.mustache
This PR is related to issue #224
> Scripts added to plugin package.json

- templates/plugin-bootstrap.mustache
// WPCS: XSS ok. is depreciated and should be replaced with // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
https://github.com/WordPress/WordPress-Coding-Standards/wiki/Whitelisting-code-which-flags-errors#escaping--xss
> Fix deprecated whitelist code flag

- templates/plugin-readme.mustache
Add minimum required PHP version header in plugin's readme file.
https://make.wordpress.org/plugins/2017/08/29/minimum-php-version-requirement/
> Required PHP version header

- templates/install-wp-tests.sh
The SVN externals aren't necessary in this context because we only need the test suite data
> Include `--ignore-externals` when running svn co

- features/install-wp-tests.feature
- templates/install-wp-tests.sh
Fixed in issue in which the init script would fail if the database was already created. See #228 for details. I'm more than happy to write tests or whatever else is needed to get this in.
> Fixed 228 - init script can be used repeatedly

- templates/install-wp-tests.sh
Follow to the commit in WP Core https://github.com/WordPress/wordpress-develop/blob/e72fff9ceffb41d22c48febfc5f97c0cd46f5884/wp-tests-config-sample.php
As previous version of wp-tests-config-sample.php can be downloaded with previous WP Core version, I keep replacement of `dirname( __FILE__ )`, and add replacement of `__DIR__`.
> Code Modernization: Replace `dirname( __FILE__ )` calls with `__DIR__` magic constant.

- templates/install-wp-tests.sh
Since some platforms (such as Travis CI) use empty passwords for the database user, passing an empty string for `$DB_PASS` can result in a TTY prompt, e.g.:
```sh
$ DB_USER=someuser DB_PASS="" mysql -u "$DB_USER" -p"$DB_PASS" -e 'show databases;'
Enter password:
```
In a CI environment, [this can cause the entire pipeline to hang until cancelled](https://travis-ci.org/github/nexcess/woocommerce-limit-orders/jobs/667345104#L290).
This PR rewrites the call to use the longer option names (`--user`, `--password`, and `--execute`) to prevent empty passwords from being interpreted as "please ask me to provide my password in an interactive prompt."
> Use longer option names in `install_db()` to avoid stalling CIs

- .travis.yml
- composer.json
- features/scaffold.feature
This PR changes the Travis CI configuration to use the `xenial` Ubuntu distribution instead of the `trusty` one by default.
> Bump Travis CI OS from `trusty` to `xenial`

- features/scaffold-plugin-tests.feature
- features/scaffold-theme-tests.feature
- features/scaffold.feature
- templates/.phpcs.xml.dist
- templates/plugin-travis.mustache
- Removes tests for PHP 5.3 to adapt to WP minimum of PHP 5.6+
- Add PHPCompatibility rule sets
- Adapt tests
All credits go to @whoisnegrello, whose original PR #258 I accidentally erased.
> Update plugin/theme test scaffolding

- templates/plugin-distignore.mustache
`.github` workflow files is not necessary for distribution build.
> GitHub workflow files should be ignored on build

- features/scaffold-plugin-tests.feature
- features/scaffold-theme-tests.feature
- features/scaffold.feature
- templates/plugin-travis.mustache
Since current PHP recommended version is 7.3+.
@see https://wordpress.org/support/article/requirements/
> Add PHP version 7.3, 7.4 into matrix on Travis CI

- templates/install-wp-tests.sh
> WP_CORE_DIR does not need a trailing slash

- templates/install-wp-tests.sh
#249 forget to add $EXTRA parameters when check existing database.
Therefore, when we use install-wp-tests.sh to non default host DB like other Docker container,
we got error:
```console
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```
> Fix bug that can't init non default host DB

- templates/install-wp-tests.sh
This replaces the existing process of downloading the nightly .zip file with exporting a clean directory tree from https://core.svn.wordpress.org/trunk, which is more closely in sync with the unit test suite files installed during the install_test_suite() process. Additionally, using `svn export` instead of `svn co` avoids downloading the .svn directory, which is unnecessary.
Fixes #267.
> Keep test suite in sync with WP files when testing trunk/nightlies

- features/install-wp-tests.feature
- features/scaffold-theme-tests.feature
- templates/plugin-bootstrap.mustache
This PR adds support for the new PHPUnit polyfills for WP core trunk.
It also removes the distinction between running tests on PHP < 8 and PHP >= 8, as it now works across the entire version spectrum.
Fixes #285
> Fix testing on WP trunk

- README.md
- src/Scaffold_Command.php
> Deprecate `wp scaffold block` in favor of `@wordpress/create-block`

- templates/plugin-distignore.mustache
Editors like Vim and Gedit will create backup copies of a file. A file named `foobar` may get a backup copy called `.foobar~`, with the prefix of a dot and the suffix of a tilde.
This pull request adds that pattern to `.distignore`.
> Add backup files ending with tilde to .distignore

- templates/plugin-gitlab.mustache
Adds platform agnostic mysql-client packages in preparation for a migration from unmaintained tetraweb docker images.
Current functionality should be the same.
> Use platform-agnostic mysql-client packages in Gitlab CI

- templates/plugin-gitlab.mustache
Add phpcompatibility-wp coding standards to Gitlab template.
Phpcompatibility-wp is required here:
https://github.com/wp-cli/scaffold-command/blob/4a142380157b43de3179bf3a3132b97d81442e48/templates/.phpcs.xml.dist#L23
Phpcompatibility-wp is already used in Travis template:
https://github.com/wp-cli/scaffold-command/blob/4a142380157b43de3179bf3a3132b97d81442e48/templates/plugin-travis.mustache#L53-L57
Phpcompatibility-wp will always include php-compatibility and phpcompatibility-paragonie too:
https://github.com/PHPCompatibility/PHPCompatibilityWP/blob/ed2685318d3af3cd9a1676bea8e3ffc3a972b3b1/composer.json#L26
> Add phpcompatibility-wp coding standards to Gitlab template

- templates/install-wp-tests.sh
Update the URL used for db.php to reflect the proper URL from Github: https://raw.githubusercontent.com/markoheijnen/wp-mysqli/master/db.php
At the time of writing, https://raw.github.com/markoheijnen/wp-mysqli/master/db.php is throwing a 503 error (`Error 503 hostname doesn't match against certificate`). The correct raw URL doesn't 503.
> Update the github URL for db.php

- features/install-wp-tests.feature
- features/scaffold-theme-tests.feature
Tests involving the WP release can now only run on PHP 7.0+ due to the new minimum requirement.
> Run test only on PHP 7.0+

- composer.json
- scaffold-command.php
- src/Scaffold_Command.php
Auto-generated PR that updates WPCS to the latest v3 and then fixes all automatically fixable issues.
See https://github.com/wp-cli/wp-cli-tests/issues/175
> Update to WPCS v3

- features/install-wp-tests.feature
- features/scaffold-theme-tests.feature
- features/scaffold.feature
See https://github.com/wp-cli/.github/issues/94
> Add `@require-mysql` for tests with explicit MySQL dependency

- features/install-wp-tests.feature
Noticed here: https://github.com/wp-cli/automated-tests/actions/runs/8654969149/job/23733150212#step:14:230
Needed because of https://core.trac.wordpress.org/changeset/57985
> Update trunk test to require PHP 7.2

- src/Scaffold_Command.php
- templates/plugin-github.mustache
Fixes https://github.com/wp-cli/scaffold-command/issues/330
* Add `github` as valid option for `--ci` argument
* Add GitHub Actions file template
* When scaffolding, test file is copied to `.github/workflows/testing.yml`
Note:
For theme, in `theme-bootstrap.muscatche`, there is code for checking PHP version. So test is exited for PHP greater than 8.0. Is this still valid?
```
if ( PHP_MAJOR_VERSION >= 8 ) {
echo "The scaffolded tests cannot currently be run on PHP 8.0+. See https://github.com/wp-cli/scaffold-command/issues/285" . PHP_EOL; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
exit( 1 );
}
```
> Add GitHub as valid CI for plugin and theme scaffold

- features/scaffold-block.feature
- features/scaffold-theme-tests.feature
Replace P2 theme with TwentyTwelve in feature tests
Related https://github.com/wp-cli/wp-cli-tests/issues/200
> Update theme tests to remove P2 and use TwentyTwelve

- templates/theme-bootstrap.mustache
This PR removes following code from `theme-bootstrap.mustache`:
```php
if ( PHP_MAJOR_VERSION >= 8 ) {
echo "The scaffolded tests cannot currently be run on PHP 8.0+. See https://github.com/wp-cli/scaffold-command/issues/285" . PHP_EOL; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
exit( 1 );
}
```
While working on https://github.com/wp-cli/scaffold-command/pull/331 I noticed this conditional is now not needed.
CC @schlessera - Ref https://github.com/wp-cli/scaffold-command/issues/285
> Scaffold theme test should work in PHP greater than 8.0

- features/scaffold-plugin-tests.feature
- src/Scaffold_Command.php
- templates/plugin-bootstrap.mustache
Fixes https://github.com/wp-cli/scaffold-command/issues/190
* Use correct plugin main file in `tests/bootstrap.php` for in scaffolded tests
* Fallback name will be same as of now `plugin-slug.php`
* Feature test is also added
> Correct plugin main file in bootstrap in scaffolded test

- features/scaffold-plugin-tests.feature
- src/Scaffold_Command.php
Currently `bitbucket` is not accepted in `--ci` in `scaffold plugin` but in `scaffold plugin-tests` we have already implemented `bitbucket` CI. So, this PR adds `bitbucket` as valid CI in `scaffold plugin` and related scenario in feature test.
> Accept Bitbucket as valid CI in scaffold plugin

- features/scaffold-plugin-tests.feature
- features/scaffold-theme-tests.feature
- templates/plugin-bitbucket.mustache
Fixes https://github.com/wp-cli/scaffold-command/issues/197
* Removed older PHP versions and add test for newer PHP versions
> Update Bitbucket CI

- templates/install-wp-tests.sh
Hi,
This PR adds checks for missing dependencies (svn, curl, wget) to ensure the script exits gracefully if any are missing. It also improves error handling in the download process to prevent incomplete setups when required tools are unavailable.
> Add dependency checks and error handling for svn and download tools

- templates/phpunit.xml.dist
Since PHPUnit 9.5.10 and 8.5.21, PHP deprecations are no longer converted to exceptions by default (`convertDeprecationsToExceptions="true"` can be configured to enable this).
This commit reverts PHPUnit to the previous behaviour by adding `convertDeprecationsToExceptions="true"` to the PHPUnit configuration. It also adds the other related directives for consistency.
See similar change in core: https://github.com/WordPress/wordpress-develop/commit/7c2b54e0275201a07c145de5c705545ef58ebda7
> PHPUnit template: convert deprecations to exceptions

- src/Scaffold_Command.php
- templates/child_theme_functions.mustache
Related https://github.com/wp-cli/scaffold-command/issues/109
* Function prefix should be of child theme, not parent theme
* Fixed WPCS issues in the mustache template
> Update templates for child theme scaffolding
